package ;
import rethinkdb.RethinkDB.r;
import rethinkdb.reql.*;
using tink.CoreApi;

@:await class TestArity extends TestBase {
	@:async
	override function test() {
		var _tables = ["tbl"];
		@:await createTables(_tables);
		var tbl = r.db("test").table("tbl");
		var db = r.db("test");
		var obj = r.expr({ "a" : 1 });
		var array = r.expr([1]);
		@:await assertError("ReqlCompileError", "Expected 0 arguments but found 1.", r.dbList(1));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", tbl.zip(1));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", tbl.isEmpty(1));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", obj.keys(1));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", tbl.distinct(1));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", tbl.delete(1));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.dbCreate());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.dbDrop());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.db());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.floor());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.ceil());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.round());
		@:await assertError("ReqlQueryLogicError", "Empty ERROR term outside a default block.", r.error());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 0.", r.js());
		@:await assertErrorRegex("TypeError", ".* takes at least 1 (?:positional )?argument \(0 given\)", r.expr());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.concatMap());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.skip());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.limit());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.append());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.prepend());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.difference());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.setInsert());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.setUnion());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.setIntersection());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", array.setDifference());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.nth());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.forEach());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.get());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", r.expr([]).sample());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.offsetsOf());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.dbCreate(1, 2));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.dbDrop(1, 2));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.db(1, 2));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.floor(1, 2));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.ceil(1, 2));
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.round(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.filter());
		@:await assertError("ReqlCompileError", "Expected between 0 and 1 arguments but found 2.", r.error(1, 2));
		@:await assertError("ReqlQueryLogicError", "Expected type DATUM but found DATABASE:", db.tableDrop());
		@:await assertError("ReqlQueryLogicError", "Expected type DATUM but found DATABASE:", db.tableCreate());
		@:await assertError("ReqlCompileError", "Expected 1 argument but found 2.", r.js(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.concatMap(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.skip(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.limit(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.append(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.prepend(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.difference([], []));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.setInsert(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.setUnion([1], [2]));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.setIntersection([1], [2]));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", array.setDifference([1], [2]));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.nth(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.forEach(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.get(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", r.expr([]).sample(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 3.", tbl.offsetsOf(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 4.", tbl.filter(1, 2, 3));
		@:await assertError("ReqlCompileError", "Expected between 1 and 2 arguments but found 3.", db.tableDrop(1, 2));
		@:await assertError("ReqlCompileError", "Expected between 2 and 3 arguments but found 1.", r.expr([]).deleteAt());
		@:await assertError("ReqlCompileError", "Expected between 1 and 2 arguments but found 3.", db.tableCreate(1, 2));
		@:await assertError("ReqlCompileError", "Expected between 1 and 2 arguments but found 3.", tbl.count(1, 2));
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.update());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.replace());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.insert());
		@:await assertError("ReqlQueryLogicError", "Expected type DATUM but found DATABASE:", db.table());
		@:await assertError("ReqlCompileError", "Expected 2 arguments but found 1.", tbl.reduce());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 1.", tbl.eqJoin());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 1.", tbl.innerJoin());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 1.", tbl.outerJoin());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 1.", r.expr([]).insertAt());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 1.", r.expr([]).spliceAt());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 1.", r.expr([]).changeAt());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", tbl.eqJoin(1));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", tbl.innerJoin(1));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", tbl.outerJoin(1));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", r.expr([]).insertAt(1));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", r.expr([]).spliceAt(1));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", r.expr([]).changeAt(1));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 5.", tbl.eqJoin(1, 2, 3, 4));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 4.", tbl.innerJoin(1, 2, 3));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 4.", tbl.outerJoin(1, 2, 3));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 4.", r.expr([]).insertAt(1, 2, 3));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 4.", r.expr([]).spliceAt(1, 2, 3));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 4.", r.expr([]).changeAt(1, 2, 3));
		@:await assertError("ReqlCompileError", "Expected 2 or more arguments but found 1.", tbl.map());
		@:await assertError("ReqlCompileError", "Expected 3 or more arguments but found 2.", r.branch(1, 2));
		@:await assertError("ReqlQueryLogicError", "Cannot call `branch` term with an even number of arguments.", r.branch(1, 2, 3, 4));
		@:await assertAtom(10, tbl.insert([{ "id" : 0 }, { "id" : 1 }, { "id" : 2 }, { "id" : 3 }, { "id" : 4 }, { "id" : 5 }, { "id" : 6 }, { "id" : 7 }, { "id" : 8 }, { "id" : 9 }]).getField("inserted"));
		@:await assertBag([0, 1, 2], tbl.getAll(0, 1, 2).getField("id"));
		@:await assertBag([0, 1, 2], tbl.getAll(r.args([]), 0, 1, 2).getField("id"));
		@:await assertBag([0, 1, 2], tbl.getAll(r.args([0]), 1, 2).getField("id"));
		@:await assertBag([0, 1, 2], tbl.getAll(r.args([0, 1]), 2).getField("id"));
		@:await assertBag([0, 1, 2], tbl.getAll(r.args([0, 1, 2])).getField("id"));
		@:await assertBag([0, 1, 2], tbl.getAll(r.args([0]), 1, r.args([2])).getField("id"));
		@:await assertAtom(1, r.branch(true, 1, r.error("a")));
		@:await assertAtom(1, r.branch(r.args([true, 1]), r.error("a")));
		@:await assertAtom(1, r.expr(true).branch(1, 2));
		@:await assertError("ReqlUserError", "a", r.branch(r.args([true, 1, r.error("a")])));
		@:await assertAtom(([{ "group" : 0, "reduction" : 1 }]), tbl.group(function(row) return row["id"].mod(2)).count({ "id" : 0 }).ungroup());
		@:await assertAtom(([{ "group" : 0, "reduction" : 1 }]), tbl.group(r.row["id"].mod(2)).count(r.args([{ "id" : 0 }])).ungroup());
		@:await assertAtom(({ "a" : { "c" : 1 } }), r.expr({ "a" : { "b" : 1 } }).merge(r.args([{ "a" : r.literal({ "c" : 1 }) }])));
		@:await assertErrorRegex("TypeError", ".*takes exactly 1 argument \(2 given\)", r.http("httpbin.org/get", "bad_param"));
		@:await assertErrorRegex("TypeError", ".*takes exactly 1 argument \(2 given\)", r.binary("1", "2"));
		@:await assertErrorRegex("TypeError", ".*takes exactly 1 argument \(0 given\)", r.binary());
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 2.", tbl.indexRename("idx"));
		@:await assertError("ReqlCompileError", "Expected 3 arguments but found 4.", tbl.indexRename("idx", "idx2", "idx3"));
		@:await assertError("ReqlServerCompileError", "Expected 0 arguments but found 1.", r.now("foo"));
		@:await assertError("ReqlQueryLogicError", "Expected 0 arguments but found 3.", r.now(r.args([1, 2, 3])));
		@:await dropTables(_tables);
		return Noise;
	}
}